project:
  type: default
  output-dir: _slides
  render:
    - working-with-data/descriptive-statistics.qmd
    - working-with-data/graphical-visualization.qmd

author:
  - name: '[Sven Rieger](<https://riegersven.github.io/>)'
    affiliation:
    - name: University of Tübingen
      city: Tübingen
      url: https://uni-tuebingen.de/
    email: sven.rieger@uni-tuebingen.de
    email-obfuscation: javascript
    orcid: 0000-0002-0339-0695

format:
  revealjs:
    embed-resources: true
    slide-level: 3
    smaller: true
    scrollable: true
    navigation-mode: linear
    progress: true
    keyboard: true
    controls: true
    controls-tutorial: true
    controls-layout: edges
    mouse-wheel: false
    slide-number: c/t
    show-slide-number: all
    reference-location: document
    theme: [simple, revealjs-styles.scss]
    include-after-body: include/webex.js

execute:
  freeze: true
  cache: false